### ISSUE TITLE
Provide a simple possibility to update theme

### ISSUE THREAD

**Issue by almir-s** [elvisoric/dotfiles#10]
Since by default 'rose-pine' theme is enabled, it is confusing what needs to be changed in order to change the default theme. 
When updating theme throgh the command (for example `colorscheme lunaperce`) the change is valid only for the current session and on nvim restart, the old theme is applied again.

Remove unused files such as colors.lua.

**Comment by elvisoric** [comment]
The idea behind the `colors.lua` is to provide simple place to change the theme. 
You can just open `colors.lua` and provide an argument to `ChangeDefaultTheme` function, like this:
https://github.com/elvisoric/dotfiles/blob/main/nvim/after/plugin/colors.lua#L7 
Notice that I have changed the name of the function from: `ColorMyPencils` to `ChangeDefaultTheme`

**Comment by elvisoric** [comment]
The idea behind the `colors.lua` is to provide simple place to change the theme. 
You can just open `colors.lua` and provide an argument to `ChangeDefaultTheme` function, like this:
https://github.com/elvisoric/dotfiles/blob/main/nvim/after/plugin/colors.lua#L7 
Notice that I have changed the name of the function from: `ColorMyPencils` to `ChangeDefaultTheme`
